apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-ticket-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-ticket-app
  template:
    metadata:
      labels:
        app: train-ticket-app
    spec:
      containers:
      - name: train-ticket-app
        # REPLACE 'your-dockerhub-user' below with your actual Docker Hub username
        image: venkatasivareddybhavanam834/train-ticket-reservation:latest 
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
